package com.sleepDiary.backend.statusCodes;

public enum DBCodes {
	USER_EXISTS,
	USER_NOT_EXISTS,
	USER_ADDED,
	USER_NOT_ADDED,
	USER_DATA_INVALID,
	DOMAIN_CREATION_FAILED,
	DATA_ADDED,
	DATA_CORRUPT,
	DATA_NOT_ADDED,
	INVALID_TOKEN, 
	TAP_NOT_ADDED,
	TAP_ADDED
	

}
